name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    permissions:
      contents: write
    uses: George-Ogden/actions/.github/workflows/text-release.yaml@v4.0.1
